name = "finatrack"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "static"

[vars]
ENVIRONMENT = "production"
SUPABASE_URL = "https://ynqinvzopesauljdgjoo.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_ROu6-kwidZFNH-d2RermBg_z_zx5gPI"
